In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('sleep_deprivation_dataset_detailed.csv')
df

,Participant_ID,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,Gender,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
0,P1,5.25,15,12,1.60,64.20,12,365.85,35,Female,30.53,2,1,33
1,P2,8.70,12,14,2.54,65.27,21,288.95,20,Male,27.28,3,8,37
2,P3,7.39,17,10,3.40,74.28,35,325.93,18,Male,30.00,1,2,32
3,P4,6.59,14,3,3.54,72.42,25,276.86,18,Male,34.47,5,0,23
4,P5,3.94,20,12,3.09,99.72,60,383.45,36,Male,29.70,3,4,14
5,P6,3.94,12,6,2.84,58.80,46,224.48,28,Male,32.23,3,6,29
6,P7,3.35,8,18,3.16,50.90,31,201.56,22,Male,32.74,4,5,16
7,P8,8.20,14,21,3.28,74.69,66,388.37,29,Male,32.25,1,0,4
8,P9,6.61,12,1,1.74,58.94,38,258.28,20,Female,25.24,3,4,28
9,P10,7.25,0,9,2.61,68.32,23,221.28,18,Male,21.78,3,4,3
10,P11,3.12,6,12,2.23,87.21,37,319.04,18,Male,24.74,1,5,9
11,P12,8.82,8,24,3.91,86.05,14,215.23,25,Female,33.16,1,2,16
12,P13,7.99,0,20,2.91,65.40,56,465.99,27,Female,20.49,3,4,9
13,P14,4.27,11,5,4.45,77.13,58,208.29,28,Female,26.73,1,6,16
14,P15,4.09,7,11,2.70,75.44,39,373.66,29,Male,21.96,3,4,19
15,P16,4.10,10,11,3.95,81.82,55,331.54,30,Female,27.88,3,4,23
16,P17,4.83,18,19,3.90,62.52,61,401.61,29,Male,32.67,4,4,4
17,P18,6.15,16,10,1.95,79.49,14,298.45,31,Male,32.97,0,9,33
18,P19,5.59,7,22,3.02,98.94,21,246.51,19,Male,22.02,3,9,5
19,P20,4.75,2,24,3.59,74.34,25,494.55,36,Male,33.43,2,2,1
20,P21,6.67,2,6,4.08,95.30,35,451.68,35,Female,28.06,5,0,12
21,P22,3.84,0,0,2.48,71.72,35,458.12,20,Female,23.95,0,4,10
22,P23,4.75,4,0,2.16,67.50,57,275.08,40,Male,30.04,0,8,22
23,P24,5.20,9,24,3.63,82.26,30,211.65,34,Male,26.19,0,0,15
24,P25,5.74,6,24,3.93,83.45,48,290.98,43,Male,24.43,4,2,30
25,P26,7.71,8,19,2.55,93.21,45,361.12,25,Female,29.99,3,3,10
26,P27,4.20,6,12,1.79,61.51,42,298.00,43,Male,22.23,4,0,15
27,P28,6.09,8,8,4.32,74.96,39,448.36,27,Male,23.61,3,0,7
28,P29,6.55,7,2,2.69,78.60,46,281.46,43,Female,25.39,4,7,3
29,P30,3.28,11,6,3.05,88.43,32,489.58,19,Female,22.31,4,1,39
30,P31,6.65,1,5,4.01,52.18,67,337.18,36,Male,24.89,5,7,3
31,P32,4.02,0,7,3.53,99.73,19,452.61,26,Female,27.72,2,6,24
32,P33,3.39,15,8,3.71,73.50,63,258.31,24,Female,30.60,4,9,2
33,P34,8.69,4,4,2.13,63.98,14,323.41,21,Male,31.04,5,9,31
34,P35,8.79,2,0,3.12,94.17,45,409.85,43,Female,31.99,1,1,2
35,P36,7.85,11,18,3.59,87.39,43,241.51,38,Male,30.65,2,5,26
36,P37,4.83,7,9,2.19,97.65,61,239.82,35,Female,29.58,4,5,28
37,P38,3.59,2,11,2.02,66.54,40,490.86,30,Male,22.04,0,2,31
38,P39,7.11,0,23,4.45,77.64,19,414.38,28,Male,24.80,1,10,18
39,P40,5.64,2,14,3.05,78.61,67,212.32,41,Male,26.12,1,1,20
40,P41,3.73,4,21,2.28,99.02,28,319.65,21,Female,19.41,5,0,4
41,P42,5.97,14,23,4.49,53.77,67,330.06,42,Male,26.98,1,5,17
42,P43,3.21,13,8,4.40,65.28,41,423.21,38,Female,25.42,2,4,27
43,P44,8.46,2,19,3.17,59.55,10,275.26,42,Male,31.64,4,10,21
44,P45,4.55,0,16,4.15,63.42,65,255.30,21,Male,34.62,4,8,20
45,P46,6.98,4,16,2.07,74.26,14,224.26,27,Female,27.45,0,0,5
46,P47,4.87,13,19,2.34,68.63,54,328.49,22,Male,23.49,5,6,0
47,P48,6.12,6,11,3.60,69.73,13,406.55,26,Male,18.74,0,4,4
48,P49,6.28,8,6,4.04,92.21,25,217.46,41,Female,33.72,1,4,40
49,P50,4.11,14,1,4.07,96.50,33,474.56,20,Male,33.62,0,1,11
50,P51,8.82,14,2,2.71,53.52,25,332.71,34,Male,22.30,2,10,25
51,P52,7.65,9,16,4.16,60.45,64,271.94,20,Male,29.82,4,2,33
52,P53,8.64,12,4,4.05,83.56,11,228.16,33,Male,19.28,1,6,13
53,P54,8.37,18,16,4.31,67.93,58,254.86,21,Female,20.83,0,5,25
54,P55,6.59,6,23,3.86,62.71,37,480.38,35,Female,21.69,5,1,26
55,P56,8.53,16,16,3.51,64.76,41,391.48,34,Male,23.01,2,5,8
56,P57,3.53,19,16,3.24,66.13,36,355.01,24,Female,34.93,2,1,25
57,P58,4.18,3,1,2.62,92.43,29,397.13,41,Male,29.85,0,1,21
58,P59,3.27,4,1,4.32,56.83,33,330.70,40,Female,24.53,4,1,29
59,P60,4.95,6,21,4.42,85.45,21,419.01,22,Male,30.53,0,10,16

In [4]:
df.head(5)

,Participant_ID,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,Gender,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
0,P1,5.25,15,12,1.60,64.20,12,365.85,35,Female,30.53,2,1,33
1,P2,8.70,12,14,2.54,65.27,21,288.95,20,Male,27.28,3,8,37
2,P3,7.39,17,10,3.40,74.28,35,325.93,18,Male,30.00,1,2,32
3,P4,6.59,14,3,3.54,72.42,25,276.86,18,Male,34.47,5,0,23
4,P5,3.94,20,12,3.09,99.72,60,383.45,36,Male,29.70,3,4,14

In [5]:
df.describe()

,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.0000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,5.805500,8.316667,12.000000,3.245000,75.005833,38.1500,332.539000,29.516667,27.329333,2.383333,4.116667,17.866667
std,1.832357,5.637320,7.577845,0.827368,13.671457,17.1334,87.800288,8.168753,4.541382,1.688362,3.108717,11.015346
min,3.120000,0.000000,0.000000,1.600000,50.900000,10.0000,201.560000,18.000000,18.740000,0.000000,0.000000,0.000000
25%,4.107500,4.000000,6.000000,2.595000,64.620000,25.0000,257.535000,21.750000,23.580000,1.000000,1.000000,8.750000
50%,5.690000,8.000000,11.500000,3.260000,74.270000,37.0000,327.210000,28.500000,27.365000,2.500000,4.000000,17.500000
75%,7.285000,13.000000,19.000000,3.965000,85.600000,54.2500,402.845000,36.000000,30.747500,4.000000,6.000000,26.250000
max,8.820000,20.000000,24.000000,4.490000,99.730000,67.0000,494.550000,43.000000,34.930000,5.000000,10.000000,40.000000

In [11]:
df['Sleep_Hours'].mean()

np.float64(5.8054999999999986)

In [12]:
df['Sleep_Quality_Score'].min()

0

In [14]:
df['Sleep_Quality_Score'].max()

20

In [16]:
df[df['Sleep_Quality_Score'] > 15]

,Participant_ID,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,Gender,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
2,P3,7.39,17,10,3.40,74.28,35,325.93,18,Male,30.00,1,2,32
4,P5,3.94,20,12,3.09,99.72,60,383.45,36,Male,29.70,3,4,14
16,P17,4.83,18,19,3.90,62.52,61,401.61,29,Male,32.67,4,4,4
17,P18,6.15,16,10,1.95,79.49,14,298.45,31,Male,32.97,0,9,33
53,P54,8.37,18,16,4.31,67.93,58,254.86,21,Female,20.83,0,5,25
55,P56,8.53,16,16,3.51,64.76,41,391.48,34,Male,23.01,2,5,8
56,P57,3.53,19,16,3.24,66.13,36,355.01,24,Female,34.93,2,1,25

In [19]:
df[df['Stress_Level'] > 30]

,Participant_ID,Sleep_Hours,Sleep_Quality_Score,Daytime_Sleepiness,Stroop_Task_Reaction_Time,N_Back_Accuracy,Emotion_Regulation_Score,PVT_Reaction_Time,Age,Gender,BMI,Caffeine_Intake,Physical_Activity_Level,Stress_Level
0,P1,5.25,15,12,1.60,64.20,12,365.85,35,Female,30.53,2,1,33
1,P2,8.70,12,14,2.54,65.27,21,288.95,20,Male,27.28,3,8,37
2,P3,7.39,17,10,3.40,74.28,35,325.93,18,Male,30.00,1,2,32
17,P18,6.15,16,10,1.95,79.49,14,298.45,31,Male,32.97,0,9,33
29,P30,3.28,11,6,3.05,88.43,32,489.58,19,Female,22.31,4,1,39
33,P34,8.69,4,4,2.13,63.98,14,323.41,21,Male,31.04,5,9,31
37,P38,3.59,2,11,2.02,66.54,40,490.86,30,Male,22.04,0,2,31
48,P49,6.28,8,6,4.04,92.21,25,217.46,41,Female,33.72,1,4,40
51,P52,7.65,9,16,4.16,60.45,64,271.94,20,Male,29.82,4,2,33

In [22]:
df[df['Emotion_Regulation_Score'] < 10]

Empty DataFrame
Columns: [Participant_ID, Sleep_Hours, Sleep_Quality_Score, Daytime_Sleepiness, Stroop_Task_Reaction_Time, N_Back_Accuracy, Emotion_Regulation_Score, PVT_Reaction_Time, Age, Gender, BMI, Caffeine_Intake, Physical_Activity_Level, Stress_Level]
Index: []

In [23]:
df0 = pd.read_csv('acsdata.csv')
df0

,GEO_ID,NAME,DP02_0001E,DP02_0001M,DP02_0002E,DP02_0002M,DP02_0003E,DP02_0003M,DP02_0004E,DP02_0004M,...,DP02_0150PE,DP02_0150PM,DP02_0151PE,DP02_0151PM,DP02_0152PE,DP02_0152PM,DP02_0153PE,DP02_0153PM,DP02_0154PE,DP02_0154PM
0,Geography,Geographic Area Name,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...,Estimate!!HOUSEHOLDS BY TYPE!!Total households...,Margin of Error!!HOUSEHOLDS BY TYPE!!Total hou...,...,Percent!!ANCESTRY!!Total population!!Welsh,Percent Margin of Error!!ANCESTRY!!Total popul...,Percent!!ANCESTRY!!Total population!!West Indi...,Percent Margin of Error!!ANCESTRY!!Total popul...,Percent!!COMPUTERS AND INTERNET USE!!Total hou...,Percent Margin of Error!!COMPUTERS AND INTERNE...,Percent!!COMPUTERS AND INTERNET USE!!Total hou...,Percent Margin of Error!!COMPUTERS AND INTERNE...,Percent!!COMPUTERS AND INTERNET USE!!Total hou...,Percent Margin of Error!!COMPUTERS AND INTERNE...
1,0100000US,United States,132737146,140273,61980084,185731,22999943,89108,9593464,58633,...,0.5,0.1,1,0.1,132737146,(X),96.6,0.1,93.2,0.1